# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 12.x
        cache: 'npm'
    - run: npm install
    - run: npm install @angular/cli
    - run: npm run build 
    - run: npm test --watch=false --single-run=true --reporters=junit,progress --browser=PhantomJs
    - run: |
        echo $(pwd)
        
    - run: npm install -g sonarqube-scanner
    - name: sonar-scanner
      env:
        # add SONAR_TOKEN in the secret of the repository
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  
      run: sonar-scanner /k:angular-2-demo /n:angular-2-demo /d:sonar.login=$SONAR_TOKEN /d:sonar.host.url=$SONAR_HOST_URL /d:sonar.exclusions=**/e2a/**,**/node_modules/**,**karma.conf** /d:sonar.tests=src  /d:sonar.javascript.lcov.reportPaths=coverage/lcov.info /d:sonar.test.inclusions=**/*.spec.ts
